### ISSUE TITLE
Python v3 support

### ISSUE THREAD

**Issue by laurence-myers** [Malvineous/pyopl#1]
Thanks again for providing this library. :)

I'm updating DRO Trimmer to run on Python v3. Unfortunately, PyOPL only supports Python v2.

It looks like @adambiser has created a fork to support Python v3. I've successfully used it in DRO Trimmer. Would it be possible to publish a new official version of PyOPL with these changes?

https://github.com/Malvineous/pyopl/compare/master...adambiser:pyopl:master

**Comment by Malvineous** [comment]
I've merged in the changes but it's been over 10 years since I touched Python so I have no idea how to publish the updates!  If you are interested in taking over maintenance of the module you are welcome to, just let me know what I need to do!

**Comment by laurence-myers** [comment]
Thank you @Malvineous! Hah, I also haven't touched Python in 10 years, I'm only just picking it up again, and I've never published to PyPI. I'll work out what's required to publish a new version.

**Comment by Malvineous** [comment]
Oh that's funny!  It looks like the process has changed since last time I published.  I've added you to this repo so you can push commits to it and if you give me your PyPI username I'll add you to the PyOPL repo so you can publish the package too once you work out how it's done.

**Comment by laurence-myers** [comment]
Thanks! :)

My PyPI username is [laurence-myers](https://pypi.org/user/laurence-myers/).

**Comment by Malvineous** [comment]
Done!  Hopefully that will allow you to publish the package.

**Comment by adambiser** [comment]
Ideally, it would be nice if this code could use Py_LIMITED_API and be distributed with a single pyd instead of having to have Python version-specific files, but Py_buffer prevented that.

[It looks like Py_buffer is considered stable since 3.11](https://github.com/python/cpython/blob/main/Include/pybuffer.h)

**Comment by laurence-myers** [comment]
> Ideally, it would be nice if this code could use Py_LIMITED_API and be distributed with a single pyd instead of having to have Python version-specific files, but Py_buffer prevented that.
> 
> [It looks like Py_buffer is considered stable since 3.11](https://github.com/python/cpython/blob/main/Include/pybuffer.h)

Thanks very much for adding Python 3 compatibility! 😁

Ah interesting! I had quick glance over [the docs](https://docs.python.org/3/c-api/stable.html), sounds like it should make the library run in future Python versions without a re-build. Do you think we should still publish builds for v3.8 - 3.10, which are still "active" and getting security updates? I have a feeling there aren't many consumers of PyOPL, and I'm using 3.11, so don't mind only targetting 3.11, if it makes the build easier.

I guess we also need to build for both x86 (32-bit) and x64 (64-bit), as long as Python supports 32-bit architectures.

Here's my rough plan so far:

1. Create a branch `python-3-pypi`
2. Convert the [packaging & publishing](https://packaging.python.org/en/latest/tutorials/packaging-projects/) files
3. Add GitHub Actions to build for each supported target (combo of architecture + OS + Python version), using [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/)
4. Set up PyPI credentials for CI (I think these are set in the GitHub settings)
5. Publish to the "test PyPI" sandbox (manually triggered CI action)
6. If all good, publish to PyPI (manually triggered CI action)

Steps 4-6 could probably be done outside of CI, it's really just the builds that need to be run on each OS.

**Comment by adambiser** [comment]
You're welcome, but @Malvineous really did the heavy lifting for this.

I would say that the best course is as you said: publish pre-3.11 builds, 32- and 64-bit, then have the stable API release for 3.11 onward.

Some code changes would be needed to set up the stable API build first though.  I also think there's a flag needs to be set while compiling in order to build a stable API release.

If this code should be purely Python 3.x, all of the #if PY_MAJOR_VERSION >= 3 code can be cleaned up, too (removing the Python 2 code).
